
name: Deploy the artifact

on:
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with 
      run: ./gradlew bootBuildImage
    - uses: actions/upload-artifact@v2
    - name: Copy artifact
      with:
        name: my-artifact
        path: path/to/artifact 
