name: Deploy

on:
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with 
      run: ./gradlew bootBuildImage -P${{ GHCR_URL }} -P${{ github.actor }} -P${{ secrets.GHCR_TOKEN }}
      env:
          url: https://ghcr.io
          username: $${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
